### ISSUE TITLE
Back | Algorithm | Hook and Bearing choose

### ISSUE THREAD

**Issue by Klaimmoro** [a-givertzman/cdt-math#91]
- [x] Make choice from filtered, based on user characteristics, hooks #101 
    - [x] Create a filter, based on the [loading capacity](https://github.com/a-givertzman/cdt-math/blob/choose_hoist_rope/design/docs/algorithm/part01/initial_data.md) of the user and the hook  #98 
- [x]  Make choice the bearing, from filtered, based on user selected hook #104 
    - [x] Create a filter, based on [static load capacity](https://github.com/a-givertzman/cdt-math/blob/choose_hoist_rope/design/docs/algorithm/part01/initial_data.md) #100 
    - [x] Create a filter, based on [shank diameter](https://github.com/a-givertzman/cdt-math/blob/choose_hoist_rope/design/docs/algorithm/part02/chapter_01_choose_hook.md) #100 
      - [x] Make calculating [dynamic coefficient](https://github.com/a-givertzman/cdt-math/blob/choose_hoist_rope/design/docs/algorithm/part02/chapter_01_choose_hook.md), based on user characteristics  #95 
        - [x] Choose [ϕ2, β2 coefficient](https://github.com/a-givertzman/cdt-math/blob/choose_hoist_rope/design/docs/algorithm/part02/chapter_01_choose_hook.md), based on user [lifting class](https://github.com/a-givertzman/cdt-math/blob/choose_hoist_rope/design/docs/algorithm/part01/initial_data.md)  #55 
         - [x] Choose [steady-state lifting speed](https://github.com/a-givertzman/cdt-math/blob/choose_hoist_rope/design/docs/algorithm/part02/chapter_01_choose_hook.md), depends on [User Loading Combination](https://github.com/a-givertzman/cdt-math/blob/choose_hoist_rope/design/docs/algorithm/part01/initial_data.md) and [Lifting Mechanism Drive Type](https://github.com/a-givertzman/cdt-math/blob/choose_hoist_rope/design/docs/algorithm/part01/initial_data.md)  #92
